#server:
#  port: 9090

spring:
  application:
    name: api-eureka

eureka:
  client:
    service-url:
      defaultZone: ${API_DISCOVERY_SERVICE}
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    ip-address: ${POD_IP:}    # POD_IP 없으면 자동 탐색

management:
  endpoints:
    web:
      base-path: /api/health    # actuator의 기본 경로를 변경
      exposure:
        include: health,info    # 노출시킬 엔드포인트 지정
